### ISSUE TITLE
Can not get StatusCallback to work.

### ISSUE THREAD

**Issue by dmaciasSS** [aloha/laravel-twilio#102]
Has anyone been able to get StatusCallback to work, here's my function and I get a message saying that i have an invalid From number.

$twilio->message('+1xxxxxx0458', 'Elephants!', array('StatusCallback'=>'http://url.com/status'));

**Comment by hannesvdvreken** [comment]
I think this has more to do with your settings than with the status callback option. Check if you can send a message without the callback option.

**Comment by dmaciasSS** [comment]
I can send messages without a callback and if I use the regular php-sdk I do get a callback. Any other ideas.

**Comment by hannesvdvreken** [comment]
- Which version do you use?
- Have you tried using different credentials?
- Can you create testing credentials you can share here?
- Is it a setting in Twilio to enable your callback for a specific from number?
- Have you tried getting feedback from Twilio PHP SDK by adding an issue there?

**Comment by dmaciasSS** [comment]
Which version do you use?
"aloha/twilio": "^2.0",
    Have you tried using different credentials?
No, do you really think this is an issue when it works with the official SDK? But I'll try different credentials.
    Can you create testing credentials you can share here?
Let me figure out how to do that.
    Is it a setting in Twilio to enable your callback for a specific from number?
So, based on the documentation, you setup a callback on the specific SMS message. The only callback you can set is for calls.
    Have you tried getting feedback from Twilio PHP SDK by adding an issue there?
No, since it is working for the PHP SDK.

**Comment by hannesvdvreken** [comment]
Long day at work. Not fully with you on this one.

You're saying you can't set a callback for a SMS message? Then your issue is solved no?

**Comment by dmaciasSS** [comment]
Your question was  Is it a setting in Twilio to enable your callback for a specific from number?, I meant to say that it doesn't work that way for SMS. You send the callback URL in the parameter. It's not a Twilio setting. Issue is still happening, have you tried it yourself using StatusCallback?

**Comment by hannesvdvreken** [comment]
I'm sorry, haven't got time to help you with this or try this.

This package does nothing more than configuring a Twilio SDK client. Please do some debugging and if you figured this out, please post the solution here. I'm 99% positive the problem is not in this package. If it is: I'd be happy to accept a pull request.

**Comment by dmaciasSS** [comment]
Yeah no problem, the only reason why I brought it up was because it was working on the SDK and not through this package, I'll do some more troubleshooting and see if I'm missing something or if there really is something wrong. Thanks for taking the time.

**Comment by hannesvdvreken** [comment]
Thanks. No problem. Sorry if I came across negatively. Just a long day at work

**Comment by dmaciasSS** [comment]
Not at all man, hope you get a break soon.

**Comment by dmaciasSS** [comment]
Hey @hannesvdvreken so while I don't think I know what the error is, I can give you a better clue. If you want to get a StatusCallBack based on what you find here https://www.twilio.com/docs/api/rest/sending-messages Specifically this:

> A URL that Twilio will POST to each time your message status changes to one of the following: queued, failed, sent, delivered, or undelivered. Twilio will POST the MessageSid along with the other standard request parameters as well as MessageStatus and ErrorCode. If this parameter passed in addition to a MessagingServiceSid, Twilio will override the Status Callback URL of the Messaging Service.

Using your great package you can't use the message() function, you have to use the messageWithMedia() function. This function then passes your $mediaUrls on to Twilio and you get your StatusCallBack as expected. If you look at the PHP SDK and how they are processing sendMessage() you'll see what needs to change https://github.com/twilio/twilio-php/blob/master/Services/Twilio/Rest/Messages.php. Now, I'm still trying to figure out how to do a PR and to see if I can fix it myself. However, if your intent is to keep message and messageWithMedia working like that let me know.

Thank you.

**Comment by hannesvdvreken** [comment]
Update the package to the latest version and you can do Twilio::getTwilio() which will return a configured Service_Twilio object. You can do whatever you want with it.

**Comment by dmaciasSS** [comment]
Does that mean that there is no issue with the package and that's how it's supposed to work?

**Comment by hannesvdvreken** [comment]
It means this package doesn't limit you to the methods that are defined in the interface.

**Comment by cbj4074** [comment]
I had (what I thought was) the exact same issue, whereby I was passing a `statusCallback` URL, but Twilio would never make requests to it.

As it turns-out, the property names seem to be case-sensitive, and changing `statusCallback` to `StatusCallback` fixed the issue. (I could have sworn that I saw instances of `statusCallback` in the Twilio documentation, with the lower-case leading `s`, but I can't find any now...)

In any case, I can confirm that this works as @hannesvdvreken explained earlier in the thread:

    $params = [
        'StatusCallback' => 'https://example.com/twilio/callback',
        'StatusCallbackEvent' => [
            'queued', 'failed', 'sent', 'delivered', 'undelivered'
        ]
    ];

    Twilio::message($to, $message, null, $params);

The above approach is functionally identical to this one, which demonstrates using the `Twilio::getTwilio()` method to access the underlying `Service_Twilio` object:

    $twilio = Twilio::getTwilio();

    $twilio->account->messages->sendMessage($from, $to, $message, null, $params);

So, yes, this does work as described. Double-check the case of your property names if it doesn't seem to work!
